# Set your own token and setup Github to post to /YOUR_TOKEN
github_token: SNIP789MATE

# Your hudson server url
hudson_url: http://jenkins.snipmate.com

# The base hudson job. The configuration will be copy from it.
# If the base name contains 'master', then 'master' will be replaced by the
# branch name. The branch name will be appended otherwise.
base_job: snipmate

# In case you have multiple base jobs, use the following:
# base_jobs:
#   - my_project_master_rspec
#   - my_project_master_cucumber

# Username and password for hudson. Uncomment if needed
# username: 
# password:
